stages:
  - dockerbuild-push

package:
  only: 
    - main
  image: docker:latest
  stage: dockerbuild-push
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $PERSONAL_ACCESS_TOKEN registry.gitlab.com
  script:
    - docker build -t registry.gitlab.com/s2ujeong1/bucketlist/bucket_list .
    - docker push registry.gitlab.com/s2ujeong1/bucketlist
  after_script:
    - docker logout