
server:
  servlet:
    encoding:
      force-response: true
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

google:
  map:
    key: test   # 가짜 키(진짜는 환경변수에 숨겨둠)

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 784534608821-4arov6mqr5uf6rbt1p0mm5fo9rpl4s2r.apps.googleusercontent.com
            client-secret: aaa
            scope: profile,email
          # 네이버는 spring security가 기본적을 제공해주지 않기 때문에 github, google과 달리 많은 정보를 적어줘야한다.
          naver:
            client-id: p9eywB6xBBrwCAglysCB
            client-secret: aaa
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization_grant_type: authorization_code
            scope: name,email
            client-name: Naver
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
