
server:
  servlet:
    encoding:
      force-response: true
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        show-sql: true
        format_sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 784534608821-4arov6mqr5uf6rbt1p0mm5fo9rpl4s2r.apps.googleusercontent.com
            client-secret: aaa
            scope: profile,email
          # 네이버는 spring security가 기본적을 제공해주지 않기 때문에 github, google과 달리 많은 정보를 적어줘야한다.
          naver:
            client-id: p9eywB6xBBrwCAglysCB
            client-secret: aaa
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization_grant_type: authorization_code
            scope: name,email
            client-name: Naver
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
  main:
    allow-bean-definition-overriding: true
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false

google:
  map:
    key: test   # 가짜 키(진짜는 환경변수에 숨겨둠)

logging.level:
    org.hibernate.SQL : debug

# Post Image를 위한 환경변수 추가
cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}       # AWS IAM AccessKey
      secretKey: ${AWS_SECRET_ACCESS_KEY}   # AWS IAM SecretKey
    s3:
      bucket: bucketlist-post-image-bucket    # 버킷 이름
    region:
      static: ap-northeast-2
    stack:
      auto: false

servlet:
  multipart:
    max-file-size: 50MB
    max-request-size: 50MB

# ProfileService에서 사용 할 image file path
file:
  path: C:/User/c/git/bucketlist/image/
